#==========================================================
#= PriceArt Web Service - Versione Base
#==========================================================

server:
  port: 5071
  
logging:
  level:
    it.ghismo: DEBUG
    
services:
  gestuser:
    url: http://localhost:8019/api/utenti/cerca/userid/
    security-uid: UserRead
    security-pwd: read$
    

spring:
  profiles:
    active: list1
  application:
    name: PriceArtService

#  security:
#    user:
#      name: pupetto
#      password: pupetto$

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  datasource:
    initialization-mode: always
    password: banana
    platform: postgres
    url: jdbc:postgresql://192.168.1.9:5433/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
